version: "3"
services:
  app:
    build:
      context: app
    ports:
     - 8000
#    command: source ./venv/bin/activate && python3 app.py --reload --host 0.0.0.0 --port 8000
#    command:
#      - python3 uvicorn app:app
#    deploy:
#      mode: replicated
#      replicas: 2
#      update_config:
#        parallelism: 2
#        delay: 10s
#  app2:
#    build: ./app
#    command: source ./venv/bin/activate && python3 app.py --reload --host 0.0.0.0 --port 8000
#    ports:
#      - 8000
#    command:
#      - python3 uvicorn app:app

#    deploy:
#      mode: replicated
#      replicas: 2
#      update_config:
#        parallelism: 2
#        delay: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - app
